(global-set-key "\M-+" 'enlarge-window)
(global-set-key "\M--" 'shrink-window)
(global-set-key (kbd "C-d") 'kill-whole-line)
(global-set-key (kbd "M-y") 'browse-kill-ring)
(global-set-key [f1] 'magit-status)
(global-set-key [f2] 'org-capture)
